### ISSUE TITLE
 when i run  python2.7 ./pox.py forwarding.l3_learning_editted_final       i face a problem can u help me please 

### ISSUE THREAD

**Issue by teweldeggb** [aswanthpp/Analysis-of-DDoS-Attacks-in-SDN-Environments#6]
root@jack:/home/pox# python2.7 ./pox.py forwarding.l3_learning_editted_final.py
Traceback (most recent call last):
  File "./pox.py", line 43, in <module>
    from pox.boot import boot
  File "/home/pox/pox/boot.py", line 38, in <module>
    import pox.core
  File "/home/pox/pox/core.py", line 182, in <module>
    import pox.lib.recoco as recoco
  File "/home/pox/pox/lib/recoco/__init__.py", line 1, in <module>
    from .recoco import *
  File "/home/pox/pox/lib/recoco/recoco.py", line 17, in <module>
    from queue import PriorityQueue
ImportError: No module named queue
root@jack:/home/pox#

**Comment by vinaykumar19884** [comment]
> 

Hi have this issue resolved

**Comment by teweldeggb** [comment]
yes
